### PR TITLE
fix: improve background

### LINKED ISSUE #46: [FEATURE] Improve background design of NEWS page
### Detailed description

Improve background design of NEWS page

image

### Context

https://cryptoverseweb3.github.io/Cryptoverse

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SDtw20**
## Fixes Issue

Closes #46 

## Changes proposed

Modified the background

## Screenshots

Screenshot 2022-10-15 at 12 38 27 PM

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. 
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). 
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
These all of the details are empty here, will you fill in these details, will be helpful in review your code
image

**Comment by SDtw20** [comment]
> These all of the details are empty here, will you fill in these details, will be helpful in review your code image

Done

**Comment by kabir0x23** [comment]
> Done


I mean screenshots too., it will be very easy to see the changes for the maintainers
If possible

**Comment by SDtw20** [comment]
> > Done
> 
> I mean screenshots too., it will be very easy to see the changes for the maintainers If possible

You can review now

**Pull request merged**
